fieldLayouts:
  7d195bb0-24e7-4e3b-89d2-7bc66beeed09:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 21bc3439-2dcb-42a7-bbde-dc94b26436a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 832b2fab-c391-4636-8861-e55be1be4347 # Product foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f526cc6-c3a2-4ff2-b52c-0da86b4ab83f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03ed6242-e5cb-4e16-9d54-b533e178c44c # Prijs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c60796b-ef4d-4730-a401-e66f2b16b98c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e95557d-5ac7-4c7c-9765-daf798d35181 # Filter Kleding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d52580c9-e63b-4e8d-a79e-13225c42b617
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50736933-687d-42a9-8bf6-7d4dbbe01985
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b2453c63-010c-48fe-84f5-2dd5f5249760 # Kleding
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
