fieldLayouts:
  e68d199f-a473-4e16-a20f-380757cdd09d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66689559-1617-4067-8efc-397de664e3d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a95bfa-bee2-4bf1-a9bf-6f7f990cfd39 # Merk
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d919894-a28f-441e-bbe9-6779ddf7583c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 832b2fab-c391-4636-8861-e55be1be4347 # Product foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f69edff5-cbc7-4357-ba70-f819374a4d71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03ed6242-e5cb-4e16-9d54-b533e178c44c # Prijs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d654d7d-e1a8-435b-9bb7-76f28081f051
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61f2f0d7-5ca8-4faa-a740-35c35fc6fdd5 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2dab209-8285-4b25-a1ce-36cfe9d73f01
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18743e3b-b232-445c-afa4-17be0c51830c # Filter Sticks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9108d78b-0270-4fc1-b585-0f7ae547891c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b6b2fe2-8b5f-4ce5-9957-b795f8dd80e0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5519d04b-ef0d-4080-a816-e181742e567a # Sticks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
