fieldLayouts:
  c137ac25-ca01-44e0-8d59-a39f07b21430:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f030a765-3519-473c-91ef-cdf0620fb088
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 403ed08f-34d3-4fc3-b91d-be748660d002
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6f79622a-c0f6-4178-91ab-4ec7b4c2ede2 # Filter Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
