fieldLayouts:
  671a184d-c14d-4927-b528-03c7e5746e6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 819614e7-e6ad-496d-bba6-c89b5214c816
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75ea2b99-0054-45af-bbea-990cd68d2af0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 1bb5cbeb-d0f9-4630-852c-c5bd6e075d92 # Filter
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
