fieldLayouts:
  4da23c0b-c9ea-4a41-be34-e41b0f80efd9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3febd502-080e-49f5-8b27-8ae6ff99ff7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 832b2fab-c391-4636-8861-e55be1be4347 # Product foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85efcd2f-593a-4a3c-a0c9-7e37570c910a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03ed6242-e5cb-4e16-9d54-b533e178c44c # Prijs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d70f6cc-6e1e-4771-bee7-75e50c3b9766
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12d1629d-275c-4155-9bc3-88c0a7ccfd4c # Filter Home
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5733bd6-2e8a-40e7-9027-1347aa51a08d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1d5d28d-4686-43b8-a39a-e7e428e43223
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c5080511-9498-4759-8595-ec95dd5acff0 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
