fieldLayouts:
  2602fc8b-b7b7-4bec-a3ef-0246b8d1acc9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 243bc075-b808-4312-b866-036183ab8803
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c856655-74bf-4beb-8886-1dbf0fdedc3e # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 315dc936-a3b5-4630-83e0-4fd34907e4e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61f2f0d7-5ca8-4faa-a740-35c35fc6fdd5 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f47d6630-590d-4927-a440-56ab2aa2e27e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 871dcd9d-299d-4435-aaee-d0e75a7ba8c3
        userCondition: null
handle: header
hasTitleField: true
name: Header
section: cf36feaf-94b4-4eef-8eea-521ff95db69c # Header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
