defaultPlacement: end
enableVersioning: true
handle: accessoires
name: Accessoires
propagationMethod: all
siteSettings:
  40137e29-ca1d-4628-83ea-a42182c8d1f6: # https://hockeyshop.ddev.site
    enabledByDefault: true
    hasUrls: true
    template: accessoires/_entry
    uriFormat: 'accessoires/{slug}'
type: channel
