defaultPlacement: end
enableVersioning: true
handle: filterHome
name: 'Filter Home'
propagationMethod: all
siteSettings:
  40137e29-ca1d-4628-83ea-a42182c8d1f6: # hockeyshop
    enabledByDefault: true
    hasUrls: true
    template: filter-home/_entry
    uriFormat: 'filter-home/{slug}'
structure:
  maxLevels: null
  uid: fd8ad527-13cb-4b56-a946-53cd022ff584
type: structure
