defaultPlacement: end
enableVersioning: true
handle: filterSticks
name: 'Filter Sticks'
propagationMethod: all
siteSettings:
  40137e29-ca1d-4628-83ea-a42182c8d1f6: # hockeyshop
    enabledByDefault: true
    hasUrls: true
    template: filter/_entry
    uriFormat: 'filter/{slug}'
structure:
  maxLevels: null
  uid: 40de0f27-ddb4-47c6-b8ef-5a106cb417de
type: structure
