defaultPlacement: end
enableVersioning: true
handle: footer
name: Footer
propagationMethod: all
siteSettings:
  40137e29-ca1d-4628-83ea-a42182c8d1f6: # https://hockeyshop.ddev.site
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry
    uriFormat: footer
type: single
