defaultPlacement: end
enableVersioning: true
handle: sticks
name: Sticks
propagationMethod: all
siteSettings:
  40137e29-ca1d-4628-83ea-a42182c8d1f6: # hockeyshop
    enabledByDefault: true
    hasUrls: true
    template: sticks.twig
    uriFormat: 'sticks/{slug}'
type: channel
